import type { Auction, Lot } from '../types/auction.types'
import type { Bid } from '../types/bid.types'
import type { KycDocument } from '../types/kyc.types'
import type { AuctionParticipation } from '../types/participation.types'
import type { User } from '../types/user.types'

// ─────────────────────────────────────────────────────────────────────────────
// Mock Organisations
// ─────────────────────────────────────────────────────────────────────────────

export const mockOrgs = [
  { id: 'org-001', name: 'Quickway Auctioneers Ltd',    location: 'Kampala, Uganda' },
  { id: 'org-002', name: 'Uganda Creditors Recovery',   location: 'Entebbe, Uganda' },
  { id: 'org-003', name: 'Allied Recovery Services',    location: 'Kampala, Uganda' },
  { id: 'org-004', name: 'UN Mission Uganda',           location: 'Kampala, Uganda' },
]

// ─────────────────────────────────────────────────────────────────────────────
// Mock Auctions  (currency: UGX throughout)
// ─────────────────────────────────────────────────────────────────────────────

export const mockAuctions: Auction[] = [
  {
    id: 'auc-001',
    org_id: 'org-001',
    org_name: 'Quickway Auctioneers Ltd',
    org_location: 'Kampala, Uganda',
    title: 'Kampala Commercial Property Portfolio',
    description:
      'Mixed-use commercial properties in Kololo and Nakasero, including retail units, office space and a warehouse in Industrial Area. All properties are freehold with title deeds available for inspection.',
    status: 'live',
    starts_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 22 + 1000 * 60 * 33).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    category: 'Commercial Property',
    location: 'Kampala, Uganda',
    image_url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=640&q=80',
    lot_count: 4,
    current_bid: 480_000_000,
    bid_count: 23,
    auction_ref: '#QW-2025-0041',
    participation_fee: 500_000,
    currency: 'UGX',
    bank_details: 'Equity Bank Uganda · Account: 1006400123456 · Branch: Kampala Main · Ref: Your registered email address',
  },
  {
    id: 'auc-002',
    org_id: 'org-001',
    org_name: 'Quickway Auctioneers Ltd',
    org_location: 'Jinja, Uganda',
    title: 'Court-Ordered Vehicle Fleet Disposal',
    description:
      'Fleet of 18 vehicles liquidated by court order. Includes saloons, 4×4s, pickups and minibuses. All vehicles are sold as-is. Inspection available two days prior to auction.',
    status: 'live',
    starts_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 44).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    category: 'Vehicle & Equipment',
    location: 'Jinja, Uganda',
    image_url: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=640&q=80',
    lot_count: 18,
    current_bid: 45_000_000,
    bid_count: 41,
    auction_ref: '#QW-2025-0042',
    participation_fee: 100_000,
    currency: 'UGX',
    bank_details: 'Equity Bank Uganda · Account: 1006400123456 · Branch: Jinja · Ref: Your registered email address',
  },
  {
    id: 'auc-003',
    org_id: 'org-002',
    org_name: 'Uganda Creditors Recovery',
    org_location: 'Namanve, Uganda',
    title: 'Machinery & Industrial Equipment',
    description:
      'Industrial liquidation of a manufacturing plant in Namanve. Includes CNC machines, forklifts, generators, and workshop tools. Lot catalogue available on request.',
    status: 'live',
    starts_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 5).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    category: 'Vehicle & Equipment',
    location: 'Namanve, Uganda',
    image_url: 'https://images.unsplash.com/photo-1581091226033-d5c48150dbaa?w=640&q=80',
    lot_count: 32,
    current_bid: 78_000_000,
    bid_count: 17,
    auction_ref: '#QW-2025-0043',
    participation_fee: 75_000,
    currency: 'UGX',
    bank_details: 'Stanbic Bank Uganda · Account: 9030005678901 · Branch: Lugogo · Ref: Your registered email address',
  },
  {
    id: 'auc-004',
    org_id: 'org-004',
    org_name: 'UN Mission Uganda',
    org_location: 'Kampala, Uganda',
    title: 'UN Mission Vehicle Fleet — 50 Vehicles',
    description:
      'UN Mission Uganda is disposing of 50 field vehicles including Land Cruisers, Hilux pickups, Nissan Patrols and support vehicles. All in good working condition. Inspection 2 days prior.',
    status: 'scheduled',
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 48).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 72).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    category: 'Vehicle & Equipment',
    location: 'Kampala, Uganda',
    image_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=640&q=80',
    lot_count: 50,
    current_bid: 0,
    bid_count: 0,
    auction_ref: '#QW-2025-0044',
    participation_fee: 100_000,
    currency: 'UGX',
    bank_details: 'Equity Bank Uganda · Account: 1006400123456 · Branch: Kampala Main · Ref: Your registered email address',
  },
  {
    id: 'auc-005',
    org_id: 'org-003',
    org_name: 'Allied Recovery Services',
    org_location: 'Kampala, Uganda',
    title: 'Office Furniture & IT Equipment',
    description:
      'Full liquidation of a corporate office in Nakasero. 200+ workstations, server hardware, networking equipment, executive furniture, and a boardroom set.',
    status: 'scheduled',
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 24).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 36).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    category: 'Mixed Use',
    location: 'Kampala, Uganda',
    image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=640&q=80',
    lot_count: 12,
    current_bid: 0,
    bid_count: 0,
    auction_ref: '#QW-2025-0045',
    participation_fee: 50_000,
    currency: 'UGX',
    bank_details: 'Centenary Bank Uganda · Account: 3302009876543 · Branch: Entebbe Road · Ref: Your registered email address',
  },
  {
    id: 'auc-006',
    org_id: 'org-001',
    org_name: 'Quickway Auctioneers Ltd',
    org_location: 'Mbarara, Uganda',
    title: 'Agricultural Land — Mbarara District',
    description:
      '250-acre agricultural parcel with water access in Mbarara District. Suitable for mixed farming. Title deed ready. Court-ordered sale following estate dispute.',
    status: 'scheduled',
    starts_at: new Date(Date.now() + 1000 * 60 * 60 * 96).toISOString(),
    ends_at: new Date(Date.now() + 1000 * 60 * 60 * 108).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    category: 'Agricultural Land',
    location: 'Mbarara, Uganda',
    image_url: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=640&q=80',
    lot_count: 1,
    current_bid: 0,
    bid_count: 0,
    auction_ref: '#QW-2025-0046',
    participation_fee: 150_000,
    currency: 'UGX',
    bank_details: 'Equity Bank Uganda · Account: 1006400123456 · Branch: Mbarara · Ref: Your registered email address',
  },
  {
    id: 'auc-007',
    org_id: 'org-002',
    org_name: 'Uganda Creditors Recovery',
    org_location: 'Gulu, Uganda',
    title: 'Hospitality Assets — Hotel Closure Sale',
    description:
      'Contents of a 40-room hotel including commercial kitchen equipment, laundry machines, bedroom furniture, linens, and a bar & restaurant fit-out.',
    status: 'closed',
    starts_at: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    ends_at: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    category: 'Mixed Use',
    location: 'Gulu, Uganda',
    image_url: 'https://images.unsplash.com/photo-1571003123894-1f0594d2b5d9?w=640&q=80',
    lot_count: 26,
    current_bid: 32_000_000,
    bid_count: 58,
    auction_ref: '#QW-2025-0039',
    participation_fee: 75_000,
    currency: 'UGX',
    bank_details: 'Stanbic Bank Uganda · Account: 9030005678901 · Branch: Gulu · Ref: Your registered email address',
  },
  {
    id: 'auc-008',
    org_id: 'org-001',
    org_name: 'Quickway Auctioneers Ltd',
    org_location: 'Kampala, Uganda',
    title: 'Construction Equipment Liquidation',
    description:
      'Court-ordered liquidation of a construction firm. Includes excavators, bulldozers, concrete mixers, scaffolding, and site vehicles. All lots carry a reserve price.',
    status: 'closed',
    starts_at: new Date(Date.now() - 1000 * 60 * 60 * 120).toISOString(),
    ends_at: new Date(Date.now() - 1000 * 60 * 60 * 96).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 144).toISOString(),
    category: 'Vehicle & Equipment',
    location: 'Kampala, Uganda',
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=640&q=80',
    lot_count: 9,
    current_bid: 54_000_000,
    bid_count: 34,
    auction_ref: '#QW-2025-0040',
    participation_fee: 100_000,
    currency: 'UGX',
    bank_details: 'Equity Bank Uganda · Account: 1006400123456 · Branch: Kampala Main · Ref: Your registered email address',
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Mock Lots
// ─────────────────────────────────────────────────────────────────────────────

export const mockLots: Lot[] = [
  // ── auc-004: UN Mission Vehicle Fleet (Vehicles catalogue) ───────────────
  {
    id: 'lot-004',
    auction_id: 'auc-004',
    lot_number: 1,
    title: '2020 Toyota Land Cruiser 76 Series',
    description: 'White hardtop 4WD, manual, used in field operations. Good condition.',
    reserve_price: 38_000_000,
    current_bid: 0,
    bid_increment: 500_000,
    winner_id: null,
    status: 'open',
    specs: {
      Year: '2020',
      Make: 'Toyota',
      Model: 'Land Cruiser 76',
      Mileage: '48,000 km',
      Colour: 'White',
      Condition: 'Good',
      Engine: '4.5L V8 Diesel',
      Transmission: 'Manual',
      'VIN (masked)': 'JTEBU****00123',
    },
    image_url: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?w=640&q=80',
    bid_count: 0,
  },
  {
    id: 'lot-005',
    auction_id: 'auc-004',
    lot_number: 2,
    title: '2019 Toyota Hilux D/Cab 4×4',
    description: 'White pickup, dual cab. Minor body wear. Full service records available.',
    reserve_price: 28_000_000,
    current_bid: 0,
    bid_increment: 250_000,
    winner_id: null,
    status: 'open',
    specs: {
      Year: '2019',
      Make: 'Toyota',
      Model: 'Hilux Double Cab',
      Mileage: '71,500 km',
      Colour: 'White',
      Condition: 'Good',
      Engine: '2.8L Diesel Turbo',
      Transmission: 'Manual',
      'VIN (masked)': 'MR0****90KA4577',
    },
    image_url: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?w=640&q=80',
    bid_count: 0,
  },
  {
    id: 'lot-006',
    auction_id: 'auc-004',
    lot_number: 3,
    title: '2021 Nissan Patrol Y62',
    description: 'White 4WD SUV. Excellent condition, low mileage, factory options intact.',
    reserve_price: 55_000_000,
    current_bid: 0,
    bid_increment: 1_000_000,
    winner_id: null,
    status: 'open',
    specs: {
      Year: '2021',
      Make: 'Nissan',
      Model: 'Patrol Y62',
      Mileage: '29,000 km',
      Colour: 'White',
      Condition: 'Excellent',
      Engine: '5.6L V8 Petrol',
      Transmission: 'Automatic',
      'VIN (masked)': 'JN8AY2****C9012',
    },
    image_url: 'https://images.unsplash.com/photo-1469285994282-454ceb49e63c?w=640&q=80',
    bid_count: 0,
  },
  {
    id: 'lot-007',
    auction_id: 'auc-004',
    lot_number: 4,
    title: '2018 Toyota Hiace Ambulance Conversion',
    description: 'White, converted for medical use. Stretcher and basic fittings still fitted. Interior as-is.',
    reserve_price: 22_000_000,
    current_bid: 0,
    bid_increment: 250_000,
    winner_id: null,
    status: 'open',
    specs: {
      Year: '2018',
      Make: 'Toyota',
      Model: 'Hiace Commuter',
      Mileage: '112,000 km',
      Colour: 'White',
      Condition: 'Fair',
      Engine: '2.7L Petrol',
      Transmission: 'Manual',
      'VIN (masked)': 'JTFSX22P****3340',
    },
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=640&q=80',
    bid_count: 0,
  },
  {
    id: 'lot-008',
    auction_id: 'auc-004',
    lot_number: 5,
    title: '2020 Toyota Land Cruiser 79 Pickup',
    description: 'White single cab pickup. Heavy-duty bull bar fitted. Good running condition.',
    reserve_price: 42_000_000,
    current_bid: 0,
    bid_increment: 500_000,
    winner_id: null,
    status: 'open',
    specs: {
      Year: '2020',
      Make: 'Toyota',
      Model: 'Land Cruiser 79',
      Mileage: '63,200 km',
      Colour: 'White',
      Condition: 'Good',
      Engine: '4.2L Diesel',
      Transmission: 'Manual',
      'VIN (masked)': 'JTERB71J****8801',
    },
    image_url: 'https://images.unsplash.com/photo-1614027164847-1b28cfe1df60?w=640&q=80',
    bid_count: 0,
  },

  // ── auc-001: Kampala Commercial Property Portfolio (Property catalogue) ──
  {
    id: 'lot-009',
    auction_id: 'auc-001',
    lot_number: 1,
    title: 'Kololo Retail Unit — Ground Floor',
    description: 'Commercial retail space in prime Kololo location. Freehold title. Vacant possession at transfer.',
    reserve_price: 180_000_000,
    current_bid: 195_000_000,
    bid_increment: 5_000_000,
    winner_id: null,
    status: 'open',
    specs: {
      'Property Type': 'Commercial',
      Size: '240 sqm',
      Location: 'Kololo Hill Drive, Kampala',
      Tenure: 'Freehold',
    },
    image_url: 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=640&q=80',
    bid_count: 8,
  },
  {
    id: 'lot-010',
    auction_id: 'auc-001',
    lot_number: 2,
    title: 'Nakasero Office Block — 2nd Floor',
    description: '3-room office suite with reception area. Leasehold on 49-year lease, 36 years remaining.',
    reserve_price: 120_000_000,
    current_bid: 128_000_000,
    bid_increment: 2_000_000,
    winner_id: null,
    status: 'open',
    specs: {
      'Property Type': 'Commercial',
      Size: '180 sqm',
      Location: 'Parliamentary Avenue, Nakasero',
      Tenure: 'Leasehold',
    },
    image_url: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=640&q=80',
    bid_count: 6,
  },
  {
    id: 'lot-011',
    auction_id: 'auc-001',
    lot_number: 3,
    title: 'Industrial Area Warehouse',
    description: 'Large warehouse with loading bay, 3-phase electricity, and security perimeter. Freehold.',
    reserve_price: 250_000_000,
    current_bid: 265_000_000,
    bid_increment: 5_000_000,
    winner_id: null,
    status: 'open',
    specs: {
      'Property Type': 'Commercial',
      Size: '1,200 sqm',
      Location: 'Industrial Area, Kampala',
      Tenure: 'Freehold',
    },
    image_url: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=640&q=80',
    bid_count: 9,
  },

  // ── auc-002: Court-Ordered Vehicle Fleet (existing vehicle auction) ───────
  {
    id: 'lot-001',
    auction_id: 'auc-002',
    lot_number: 1,
    title: '2019 Toyota Land Cruiser Prado TX',
    description: 'Pearl White, 4WD, Automatic, 72,000 km. Full service history. Minor scratches on rear bumper.',
    reserve_price: 32_000_000,
    current_bid: 34_500_000,
    bid_increment: 500_000,
    winner_id: null,
    status: 'open',
    specs: {
      Mileage: '72,000 km',
      Colour: 'Pearl White',
      Drivetrain: '4WD',
      Engine: '2.8L Diesel Turbo',
      Transmission: 'Automatic',
      Year: '2019',
      'VIN (masked)': 'JTEBU5J****5678',
    },
    image_url: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=640&q=80',
    bid_count: 12,
  },
  {
    id: 'lot-002',
    auction_id: 'auc-002',
    lot_number: 2,
    title: '2021 Isuzu D-Max Double Cab',
    description: 'Silver, 4WD, Manual. Heavy-duty tray fitted. 54,000 km. No accidents on record.',
    reserve_price: 25_000_000,
    current_bid: 26_500_000,
    bid_increment: 500_000,
    winner_id: null,
    status: 'open',
    specs: {
      Mileage: '54,000 km',
      Colour: 'Silver',
      Drivetrain: '4WD',
      Engine: '3.0L Diesel',
      Transmission: 'Manual',
      Year: '2021',
      'VIN (masked)': 'JADC****00P4321',
    },
    image_url: 'https://images.unsplash.com/photo-1611016186353-9af58c69a533?w=640&q=80',
    bid_count: 9,
  },
  {
    id: 'lot-003',
    auction_id: 'auc-002',
    lot_number: 3,
    title: '2018 Toyota Hiace Commuter 15-Seater',
    description: 'White minibus, 165,000 km. Good working condition. Minor body dents.',
    reserve_price: 18_000_000,
    current_bid: 19_000_000,
    bid_increment: 250_000,
    winner_id: null,
    status: 'open',
    specs: {
      Mileage: '165,000 km',
      Colour: 'White',
      Drivetrain: 'RWD',
      Engine: '2.7L Petrol',
      Transmission: 'Manual',
      Year: '2018',
      'VIN (masked)': 'JTFSX22P****9012',
    },
    image_url: 'https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?w=640&q=80',
    bid_count: 7,
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Mock Bids
// ─────────────────────────────────────────────────────────────────────────────

export const mockBids: Bid[] = [
  // lot-001 (Land Cruiser) bids
  { id: 'bid-012', lot_id: 'lot-001', bidder_id: 'user-019', amount: 34_500_000, created_at: new Date(Date.now() - 1000 * 60 * 4).toISOString() },
  { id: 'bid-011', lot_id: 'lot-001', bidder_id: 'user-007', amount: 34_000_000, created_at: new Date(Date.now() - 1000 * 60 * 11).toISOString() },
  { id: 'bid-010', lot_id: 'lot-001', bidder_id: 'user-031', amount: 33_500_000, created_at: new Date(Date.now() - 1000 * 60 * 19).toISOString() },
  { id: 'bid-009', lot_id: 'lot-001', bidder_id: 'user-019', amount: 33_000_000, created_at: new Date(Date.now() - 1000 * 60 * 34).toISOString() },
  { id: 'bid-008', lot_id: 'lot-001', bidder_id: 'user-007', amount: 32_500_000, created_at: new Date(Date.now() - 1000 * 60 * 52).toISOString() },
  // lot-002 (Isuzu D-Max) bids
  { id: 'bid-007', lot_id: 'lot-002', bidder_id: 'user-031', amount: 26_500_000, created_at: new Date(Date.now() - 1000 * 60 * 8).toISOString() },
  { id: 'bid-006', lot_id: 'lot-002', bidder_id: 'user-019', amount: 26_000_000, created_at: new Date(Date.now() - 1000 * 60 * 22).toISOString() },
  { id: 'bid-005', lot_id: 'lot-002', bidder_id: 'user-007', amount: 25_500_000, created_at: new Date(Date.now() - 1000 * 60 * 41).toISOString() },
  // lot-003 (Hiace) bids
  { id: 'bid-004', lot_id: 'lot-003', bidder_id: 'user-019', amount: 19_000_000, created_at: new Date(Date.now() - 1000 * 60 * 6).toISOString() },
  { id: 'bid-003', lot_id: 'lot-003', bidder_id: 'user-031', amount: 18_750_000, created_at: new Date(Date.now() - 1000 * 60 * 18).toISOString() },
  { id: 'bid-002', lot_id: 'lot-003', bidder_id: 'user-019', amount: 18_500_000, created_at: new Date(Date.now() - 1000 * 60 * 33).toISOString() },
  { id: 'bid-001', lot_id: 'lot-003', bidder_id: 'user-007', amount: 18_250_000, created_at: new Date(Date.now() - 1000 * 60 * 55).toISOString() },
]

// ─────────────────────────────────────────────────────────────────────────────
// Mock Bidder Profile (user-019 — David Mukasa)
// ─────────────────────────────────────────────────────────────────────────────

export const mockBidderProfile: User = {
  id: 'user-019',
  email: 'david.mukasa@gmail.com',
  role: 'bidder',
  kyc_status: 'approved',
  org_id: null,
  full_name: 'David Mukasa',
  phone: '+256 772 345 678',
  address: 'Plot 24, Bukoto Street, Kampala',
  created_at: '2025-01-15T09:00:00Z',
}

// ─────────────────────────────────────────────────────────────────────────────
// Mock Bidder Profiles (for use in admin/org tables)
// ─────────────────────────────────────────────────────────────────────────────

export const mockUsers: User[] = [
  {
    id: 'user-019',
    email: 'david.mukasa@gmail.com',
    role: 'bidder',
    kyc_status: 'approved',
    org_id: null,
    full_name: 'David Mukasa',
    phone: '+256 772 345 678',
    address: 'Plot 24, Bukoto Street, Kampala',
    created_at: '2025-01-15T09:00:00Z',
  },
  {
    id: 'user-031',
    email: 'grace.nakato@yahoo.com',
    role: 'bidder',
    kyc_status: 'pending',
    org_id: null,
    full_name: 'Grace Nakato',
    phone: '+256 701 234 567',
    address: 'Entebbe Road, Wakiso',
    created_at: '2025-02-03T14:30:00Z',
  },
  {
    id: 'user-007',
    email: 'ibrahim.ssempa@outlook.com',
    role: 'bidder',
    kyc_status: 'approved',
    org_id: null,
    full_name: 'Ibrahim Ssempa',
    phone: '+256 756 890 123',
    address: 'Ntinda, Kampala',
    created_at: '2025-01-28T11:00:00Z',
  },
  {
    id: 'user-044',
    email: 'ann.akello@gmail.com',
    role: 'bidder',
    kyc_status: 'approved',
    org_id: null,
    full_name: 'Ann Akello',
    phone: '+256 782 567 890',
    address: 'Gulu Municipality, Northern Uganda',
    created_at: '2025-02-10T08:45:00Z',
  },
  {
    id: 'user-052',
    email: 'peter.odong@gmail.com',
    role: 'bidder',
    kyc_status: 'not_submitted',
    org_id: null,
    full_name: 'Peter Odong',
    phone: '+256 700 112 233',
    address: 'Lira City, Uganda',
    created_at: '2025-03-01T16:20:00Z',
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Mock Participations (for user-019)
// ─────────────────────────────────────────────────────────────────────────────

export const mockParticipations: AuctionParticipation[] = [
  {
    // auc-002 — user-019 approved
    id: 'part-001',
    auction_id: 'auc-002',
    bidder_id: 'user-019',
    payment_status: 'approved',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'EQB-20250301-001234',
    bank_transfer_proof_url: null,
    fee_amount: 100_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 20).toISOString(),
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 18).toISOString(),
    reviewer_id: 'user-admin-001',
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 22).toISOString(),
  },
  {
    // auc-001 — user-019 pending_review
    id: 'part-002',
    auction_id: 'auc-001',
    bidder_id: 'user-019',
    payment_status: 'pending_review',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'EQB-20250303-005678',
    bank_transfer_proof_url: null,
    fee_amount: 500_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    reviewed_at: null,
    reviewer_id: null,
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
  {
    // auc-004 — user-019 unpaid
    id: 'part-003',
    auction_id: 'auc-004',
    bidder_id: 'user-019',
    payment_status: 'unpaid',
    payment_method: 'bank_transfer',
    bank_transfer_ref: null,
    bank_transfer_proof_url: null,
    fee_amount: 100_000,
    currency: 'UGX',
    submitted_at: null,
    reviewed_at: null,
    reviewer_id: null,
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
  },
  {
    // auc-002 — user-007 approved
    id: 'part-004',
    auction_id: 'auc-002',
    bidder_id: 'user-007',
    payment_status: 'approved',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'EQB-20250301-007892',
    bank_transfer_proof_url: null,
    fee_amount: 100_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 23).toISOString(),
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 21).toISOString(),
    reviewer_id: 'user-admin-001',
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 25).toISOString(),
  },
  {
    // auc-002 — user-031 pending_review
    id: 'part-005',
    auction_id: 'auc-002',
    bidder_id: 'user-031',
    payment_status: 'pending_review',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'STB-20250302-009988',
    bank_transfer_proof_url: null,
    fee_amount: 100_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    reviewed_at: null,
    reviewer_id: null,
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    // auc-001 — user-007 approved
    id: 'part-006',
    auction_id: 'auc-001',
    bidder_id: 'user-007',
    payment_status: 'approved',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'EQB-20250303-011223',
    bank_transfer_proof_url: null,
    fee_amount: 500_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    reviewer_id: 'user-admin-001',
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
  },
  {
    // auc-001 — user-044 approved
    id: 'part-007',
    auction_id: 'auc-001',
    bidder_id: 'user-044',
    payment_status: 'approved',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'EQB-20250303-013344',
    bank_transfer_proof_url: null,
    fee_amount: 500_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 9).toISOString(),
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 7).toISOString(),
    reviewer_id: 'user-admin-001',
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 11).toISOString(),
  },
  {
    // auc-004 — user-031 pending_review
    id: 'part-008',
    auction_id: 'auc-004',
    bidder_id: 'user-031',
    payment_status: 'pending_review',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'STB-20250304-021100',
    bank_transfer_proof_url: null,
    fee_amount: 100_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    reviewed_at: null,
    reviewer_id: null,
    rejection_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
  },
  {
    // auc-004 — user-044 rejected
    id: 'part-009',
    auction_id: 'auc-004',
    bidder_id: 'user-044',
    payment_status: 'rejected',
    payment_method: 'bank_transfer',
    bank_transfer_ref: 'CNT-20250304-099001',
    bank_transfer_proof_url: null,
    fee_amount: 100_000,
    currency: 'UGX',
    submitted_at: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    reviewer_id: 'user-admin-001',
    rejection_reason: 'Reference number not found in bank records. Please resubmit with correct transfer reference.',
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Mock KYC Documents
// ─────────────────────────────────────────────────────────────────────────────

export const mockKycDocuments: KycDocument[] = [
  // user-019 — approved documents
  {
    id: 'kyc-001',
    user_id: 'user-019',
    document_type: 'national_id',
    file_name: 'national_id_front.jpg',
    storage_path: 'kyc-documents/user-019/national_id_front.jpg',
    status: 'approved',
    reviewer_id: 'user-admin-001',
    rejection_reason: null,
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  {
    id: 'kyc-002',
    user_id: 'user-019',
    document_type: 'utility_bill',
    file_name: 'umeme_bill_feb25.jpg',
    storage_path: 'kyc-documents/user-019/umeme_bill_feb25.jpg',
    status: 'approved',
    reviewer_id: 'user-admin-001',
    rejection_reason: null,
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 5).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 24 * 7).toISOString(),
  },
  // user-031 — pending documents (shows in AdminKycQueue)
  {
    id: 'kyc-003',
    user_id: 'user-031',
    document_type: 'passport',
    file_name: 'passport_main.jpg',
    storage_path: 'kyc-documents/user-031/passport_main.jpg',
    status: 'pending',
    reviewer_id: null,
    rejection_reason: null,
    reviewed_at: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  {
    id: 'kyc-004',
    user_id: 'user-031',
    document_type: 'utility_bill',
    file_name: 'water_bill_feb25.jpg',
    storage_path: 'kyc-documents/user-031/water_bill_feb25.jpg',
    status: 'pending',
    reviewer_id: null,
    rejection_reason: null,
    reviewed_at: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
  },
  // user-007 — rejected document
  {
    id: 'kyc-005',
    user_id: 'user-007',
    document_type: 'national_id',
    file_name: 'id_blurry.jpg',
    storage_path: 'kyc-documents/user-007/id_blurry.jpg',
    status: 'rejected',
    reviewer_id: 'user-admin-001',
    rejection_reason: 'Image is too blurry. Please upload a clear, well-lit photo of your National ID.',
    reviewed_at: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    created_at: new Date(Date.now() - 1000 * 60 * 60 * 10).toISOString(),
  },
]

// ─────────────────────────────────────────────────────────────────────────────
// Categories
// ─────────────────────────────────────────────────────────────────────────────

export const AUCTION_CATEGORIES = [
  'All',
  'Residential Property',
  'Commercial Property',
  'Industrial Property',
  'Agricultural Land',
  'Mailo Land',
  'Leasehold Property',
  'Freehold Property',
  'Strata/Apartment',
  'Mixed Use',
  'Vacant Land/Plot',
  'Vehicle & Equipment',
  'Court Order Sale',
] as const

export type AuctionCategory = (typeof AUCTION_CATEGORIES)[number]
